version: "3"
services: 
    proxy:
        build: 
            context: ./Proxy
            dockerfile: Dockerfile
        ports: 
            - "80:80"
        restart: always
    client:
        build:
            context: ./Client
            dockerfile: Dockerfile
        ports: 
            - "9000:80"
    api:
        build: 
            context: ./API
            dockerfile: Dockerfile
        ports: 
            - "5000:80"