apiVersion: apps/v1
kind: Deployment
metadata:
  name: containerninja-cleanarch-webapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: containerninja-cleanarch-webapi
  template:
    metadata:
      labels:
        app: containerninja-cleanarch-webapi
    spec:
      containers:
        - name: containerninja-cleanarch-webapi
          image: containerninja-cleanarch/webapi:latest
          imagePullPolicy: Never
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: containerninja-cleanarch-webapi
spec:
  type: NodePort
  selector:
    app: containerninja-cleanarch-webapi
  ports:
    - port: 80
      nodePort: 31000
